# Generated by Django 4.1.7 on 2023-02-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_remove_quote_created_remove_quote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
